import Head from "next/head";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Navbar from "./_components/Navbar";
import { ThemeContext } from "./_context/context";
import { ThemeProvider } from "./_context/themeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 500 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 500 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased prose dark:prose-invert`} suppressHydrationWarning>
        <ThemeProvider>
          <Navbar />
          <div className="size-full min-h-screen">
            <div className="size-full flex flex-row">
              <Sidebar />

              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
